//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompetition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompetition()
        {
            this.tblCompParticipants = new HashSet<tblCompParticipant>();
        }
    
        public int CompID { get; set; }
        public string CompName { get; set; }
        public string CompDescription { get; set; }
        public string CompDate { get; set; }
        public bool CompActive { get; set; }
        public int UserTypeID { get; set; }
    
        public virtual tblUserType tblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompParticipant> tblCompParticipants { get; set; }
    }
}
