//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompParticipant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompParticipant()
        {
            this.tblCompWinners = new HashSet<tblCompWinner>();
            this.tblCompWinners1 = new HashSet<tblCompWinner>();
            this.tblCompWinners2 = new HashSet<tblCompWinner>();
        }
    
        public int CompParticID { get; set; }
        public int CompID { get; set; }
        public int UserID { get; set; }
        public string CompParticName { get; set; }
    
        public virtual tblCompetition tblCompetition { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompWinner> tblCompWinners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompWinner> tblCompWinners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompWinner> tblCompWinners2 { get; set; }
    }
}
