//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFAQ
    {
        public int FAQID { get; set; }
        public string FAQQuestion { get; set; }
        public string FAQAnswer { get; set; }
        public System.DateTime FAQDateTime { get; set; }
        public bool FAQActive { get; set; }
    }
}
