//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFaculty()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public string FacultyID { get; set; }
        public string FacultyName { get; set; }
        public string FacultyGender { get; set; }
        public string FacultyJoiningDate { get; set; }
        public bool FacultyActive { get; set; }
        public string FacultySpecification { get; set; }
        public string FacultyEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
