//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSurvey()
        {
            this.tblSurveyQuestions = new HashSet<tblSurveyQuestion>();
        }
    
        public int SurveyID { get; set; }
        public string SurveyTitle { get; set; }
        public string SurveyDueDate { get; set; }
        public string SurveyDescription { get; set; }
        public int UserTypeID { get; set; }
        public int SurveyConducts { get; set; }
        public bool SurveyActive { get; set; }
        public string SurveyReportingDateTime { get; set; }
    
        public virtual tblUserType tblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyQuestion> tblSurveyQuestions { get; set; }
    }
}
