//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupport
    {
        public int SupportID { get; set; }
        public string SupportNumber { get; set; }
        public string SupportEmail { get; set; }
        public string SupportAddress { get; set; }
        public string SupportPerson { get; set; }
        public System.DateTime ReportingDateTime { get; set; }
        public bool SupportActive { get; set; }
    }
}
