//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSurveyQuestion()
        {
            this.tblSurveyResponses = new HashSet<tblSurveyResponse>();
        }
    
        public int SurveyQuestionID { get; set; }
        public int SurveyID { get; set; }
        public string SurveyQuestion { get; set; }
        public string SurveyOptions { get; set; }
    
        public virtual tblSurvey tblSurvey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurveyResponse> tblSurveyResponses { get; set; }
    }
}
