//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyResponse
    {
        public int SurveyResponseID { get; set; }
        public int SurveyQuestionID { get; set; }
        public string QuestionResponse { get; set; }
        public string UserID { get; set; }
    
        public virtual tblSurveyQuestion tblSurveyQuestion { get; set; }
    }
}
