//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblCompParticipants = new HashSet<tblCompParticipant>();
        }
    
        public int UserID { get; set; }
        public string AdminNo { get; set; }
        public string StaffNo { get; set; }
        public string StudentNo { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserRequestDate { get; set; }
        public int UserTypeID { get; set; }
        public bool UserActive { get; set; }
        public string UserRegStatus { get; set; }
        public string UserReqRejectReason { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompParticipant> tblCompParticipants { get; set; }
        public virtual tblFaculty tblFaculty { get; set; }
        public virtual tblStudent tblStudent { get; set; }
        public virtual tblUserType tblUserType { get; set; }
    }
}
